### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by rileyshahar** [dylanmc/cs393_vm_api#15]
Putting on my "code pedant" hat:

1. `DataSource` calls them `map`s in its APIs (e.x. `DataSource::add_map`), but `AddressSpace` calls them `mapping`s (e.x. `AddressSpace::add_mapping`).
2. `DataSource` uses `del`, but `AddressSpace` uses `remove` for their respective `remove_map` APIs.

**Comment by simanerush** [comment]
Should we agree on call these `map`s or `mapping`s?

**Comment by dylanmc** [comment]
`map` is the verb, `mapping` is the noun (what you get after you perform a map operation). I agree, I didn't do a great job keeping that straight.

**Comment by rileyshahar** [comment]
Closing because of c4ae858.
