### ISSUE TITLE
What is SonaType??

### ISSUE THREAD

**Issue by rileyshahar** [dylanmc/cs393_vm_api#17]
This is weird. The word "sonatype" does not appear in the repo, certainly not in the `.github` folder. It might be enabled somewhere in the repository settings?

**Comment by simanerush** [comment]
we should definitely get rid of it

**Comment by rileyshahar** [comment]
Looks like Dylan figured it out. Should be ok to close this.

**Comment by dylanmc** [comment]
I'm 99 % sure I "inherited" via another collaboration. Working on getting rid of it, but it's pretty clingy.
