### ISSUE TITLE
`AddressSpace` methods could use static dispatch

### ISSUE THREAD

**Issue by rileyshahar** [dylanmc/cs393_vm_api#8]
I don't think we need dynamic dispatch for these methods, since they're only dealing with one `DataSource` at once. I think only the underlying storage of mappings needs to dynamically dispatch. Using generics in these methods will allow monomorphization, which is likely faster.

**Comment by dylanmc** [comment]
Dynamic dispatch in an operating system does sound like a bad idea, so I'm in agreement here.

**Comment by rileyshahar** [comment]
The current API does need to use dynamic dispatch for the linked list of `DataSource`s in the `MapType` struct. Probably something to consider in our ultimate data structure deliberations.
